name: Publish Crate to crates.io

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
